### PR TITLE
Create Blocks in a Block Grid Area

### PR DESCRIPTION
**Pull request by nielslyngsoe**
Fixing creating Blocks inside Areas. Which was not a thing before this PR, as there was no code for this. (Hence bugfix + feature state of this PR)
This also auto generates a area alias, so it becomes easier to setup areas correctly.
Require Validation for the alias must come later when validation is an established concept.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by iOvergaard** [comment]
Don't know if it should be a part of this PR or not, but when I edit an area, I get pretty much a blank screen

image

**Comment by iOvergaard** [comment]
Deleting an area looks like this with a half-hidden confirm modal and an `[object Object]` string:

image

**Review by iOvergaard — CHANGES_REQUESTED** [review]
Not sure if I'm doing something wrong, I deleted my existing blocks and tried to insert new values to make sure I didn't have any old data saved. As shown in this video, no blocks are showing up within my areas:

https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/752371/e24e4f68-f523-498d-8312-eaafe4810c21

**Comment by nielslyngsoe** [comment]
@iOvergaard thanks for testing this.

The two first are not part of this PR, but thanks for highlighting this.

I'm not sure I understand why you have trouble on the last one. It could be related to old data, but it would be interesting to check what data problem is causing this. Would you be able to dump the data of your document and your data type, I dont think I need the document type.

Thanks

**Comment by nielslyngsoe** [comment]
@iOvergaard a little update, I have fixed the two first issues you pointed out as part of this PR. :-)

**Review by iOvergaard — APPROVED** [review]
Probably old data if it works for you. I'm going to approve and merge and we'll see when we commence another test round :)

**Pull request merged**
