### PR TITLE
Fix: inline editing mode for Block List Editor

### PR DESCRIPTION
**Pull request by nielslyngsoe**
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16298
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16777

This PR includes:

- Making the Inline Editing mode for Block List Editor work again.
- As well making the styling and interaction(use keyboard to open block) more appropriate.
- Use ContentType Icon for both Inline and not Inline mode.

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by leekelleher — APPROVED** [review]
Tested out, working great! 🚀

**Comment by Nuklon** [comment]
This isn't working correctly as UFM isn't working.

**Comment by bganser** [comment]
> This isn't working correctly as UFM isn't rendered.

I can confirm that UFM isn't working properly. Tested with a property with the alias "headline":
{=headline} was rendered in Blocklist as {=headline}.

umbraco_blocklisteditor_inlineediting

And live editing mode seems also not to be working.

**Comment by mdeslauriers-sigmund** [comment]
I also confirm that UFM isn't working. 
Should this issue be reopened or is there another already another issue for this?

**Pull request merged**
