### PR TITLE
Search input type

### PR DESCRIPTION
**Pull request by bjarnef**
## Description

With the support of [search input type in UI library](https://github.com/umbraco/Umbraco.UI/pull/635) we should use this for search and filter input fields to be more semantic correct and also provide a slightly different virtual keyboard on many devices.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [x] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by iOvergaard — APPROVED** [review]

**Comment by iOvergaard** [comment]
Looks good to me. Would you be able to fix the merge conflicts, then we can proceed to merge this PR, @bjarnef?

**Comment by bjarnef** [comment]
@iOvergaard yeah, I need to merge latest changes and probably easiest to ignore my changes and re-add these.
Apparently they are too complex to resolve 😜

image

**Comment by bjarnef** [comment]
@iOvergaard not sure what GitHub complained about here. I pulled latest changes from upstream main branched and pushed to this remote branch. There were no conflicts.

Anyway it should be ready to merge now :)

**Review by nielslyngsoe — APPROVED** [review]
looks also good to me

**Pull request merged**
