### PR TITLE
Chore: Bundle tiny-mce package

### PR DESCRIPTION
**Pull request by iOvergaard**
## Description

See https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1977 for more details about the bundling changes.

This PR bundles the Tiny-mce Package including all modules.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

### CODE REVIEW

**Review by leekelleher — COMMENTED** [review]
Tested out, the assets get minified, but I get an error when loading up the RTE in the backoffice. Associated CSS files aren't being loaded in...

Screenshot 2024-07-25 165650

I didn't get that error previously.

**Comment by iOvergaard** [comment]
Thanks, @leekelleher. Looks like the order of imports gets mixed up. Will take a look soon.

**Comment by iOvergaard** [comment]
@leekelleher I have fixed another issue for TinyMCE where the language in the iframe wasn't set correctly, however, I have been unable to reproduce your findings here.

I have deleted the `StaticAssets/wwwroot/umbraco/backoffice` folder entirely and rebuilt the branch and the rich text editor worked. Could you try again after the latest merge of the main branch, maybe that solved it?

**Comment by leekelleher** [comment]
I've re-tested this on the latest branch, but I'm still getting the same errors (with the CSS 404s and importmap).
@madsrasmussen would you be able to review this at some point? (more as a sanity check).

**Review by leekelleher — APPROVED** [review]
Retested with @madsrasmussen, turns out that the issues I was experiencing was specific with TinyMCE's Inline mode, (which currently has its own issues, see https://github.com/umbraco/Umbraco-CMS/issues/16517).

Aside from that, the bundling LGTM! 👍

**Pull request merged**
