### PR TITLE
Added arabic language

### PR DESCRIPTION
**Pull request by bergmania**
## Description

Added a arabic language file

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Motivation and context

Official support of arabic, so people do not need to install a package.

## How to test?
Go to you user and change the language. Verify arabic is available.

## Screenshots (if appropriate)
image

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [x] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/.github/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by IbrahimMNada** [comment]
As An Arabian and Arabic native speaker with tech/Umbraco background I would love to help review it. 

if you don't mind

**Review by nielslyngsoe — APPROVED** [review]

**Comment by nielslyngsoe** [comment]
Hi @IbrahimMNada 

That would be very appreciated — I have approved and merged this PR,  as it works.

But I have no way to confirm the actual translation, so that would be nice to adjust so it makes sense for the Arabic users.
So please apply any changes in additional PRs.

Thanks in advance.

**Comment by bergmania** [comment]
Hi @IbrahimMNada 

That would be very kind of you. If any thing can be translated in a better way please just make a PR with the changes.

**Comment by IbrahimMNada** [comment]
#2414 

Refer to this PR

**Comment by bassemelkadeem** [comment]
Nice done and great effort for supporting Arabic. but the direction must be RTL and the umbraco team must support styling for components to be also RTL it will be nice. i changed the direction using manifest for localization and the direction is applied but some components are not support direction to be RTL so please support to implement this in next version

**Pull request merged**
