### PR TITLE
Translations section - WIP

### PR DESCRIPTION
**Pull request by nathanwoulfe**
First cut at scaffolding out the translation section - really just wanting to confirm I'm on the right track with implementation.

We now have a list view on the translations section:
image

We can click through to edit a dictionary:
image

We have context menu actions for dictionary items:
image

We can create a new dictionary item from the context menu:
image

Move/reload context actions do nothing, delete/export/create are working (with MSW running at least, haven't run against real data).

### CODE REVIEW

**Comment by iOvergaard** [comment]
@nathanwoulfe sorry but I caused a conflict in this PR by merging your other table PR. Hope it's easy to fix :-)

**Comment by nathanwoulfe** [comment]
@iOvergaard all good, I'll keep this up to date with `main` while it's pending review.

**Comment by nathanwoulfe** [comment]
Hey @iOvergaard, as discussed, probably time to review and merge this before it gets any more ridiculously large. Whipped through today and updated to use the new actions and tree store base class.

Still needs some of the entity actions finalised, but it's complete enough to merge and address the remaining features with small PRs.

**Review by iOvergaard — APPROVED** [review]
LGTM so far

**Pull request merged**
